### ISSUE TITLE
Something up due to update 1.2.2 of node-which

### ISSUE THREAD

**Issue by jwest-rms** [IndigoUnited/node-cross-spawn-async#7] opened 2016-01-25 17:44 UTC
I have a script that spawns [mocha](https://github.com/mochajs/mocha/blob/master/bin/mocha), it recently stopped working, error-ing with `mocha\bin\mocha"' is not recognized as an internal or external command, operable program or batch file.`  Forcing the install of 1.2.1 of node-which seems to fix the issue.

**Comment by satazor** [comment] 2016-01-25 17:46
cc @isaacs 

Meanwhile I can lock down to version 1.2.1 until the issue is fixed.

**Comment by satazor** [comment] 2016-01-25 17:52
@jwest-rms can you do a console.log of `resolved` [here](https://github.com/IndigoUnited/node-cross-spawn-async/blob/ae67771bbfba31389d07e6b10a2a902c276f1d70/lib/resolveCommand.js#L21] to see if which output changed from the old to the new version?

I'm asking this because I can't debug it right now.

**Comment by jwest-rms** [comment] 2016-01-25 18:01
With node-which 1.2.1, `resolved` is the correct path to the mocha executable.  With 1.2.2, which.sync actually throws an `Error: not found: <mocha_path>`, twice. Looks like with 1.2.1 the first call to [resolveCommand](https://github.com/IndigoUnited/node-cross-spawn-async/blob/51e5611dd33c9e9f65e1f0649f81d1af3e19b2e2/lib/parse.js#L93) throws the error, but the second succeeds. With 1.2.2, the error is thrown in both cases.

**Comment by satazor** [comment] 2016-01-25 18:05
Alright so something internally in which changed.. I will lock down the version and release the it.

Then I will carefully analyse the issue and report back.

**Comment by isaacs** [comment] 2016-01-25 18:47
Huh. Can you post an issue on node which?

**Comment by satazor** [comment] 2016-01-25 18:50
@isaacs let me first investigate the cause and I will create an issue if necessary. Perhaps tonight or tomorrow.

**Comment by satazor** [comment] 2016-01-25 18:51
@jwest-rms meanwhile `2.1.7` is showing all green in appveyor.

**Comment by jwest-rms** [comment] 2016-01-25 18:52
Awesome, `2.1.7` is working for me. Thanks!

**Comment by isaacs** [comment] 2016-01-25 21:31
It looks from the error like there's a `"` that used to be stripped off and is no longer.

@jwest-rms Can you provide a link to the repro case?  I might be able to help @satazor track down the issue, since it does seem like it's probably due to the node-which update.

**Comment by isaacs** [comment] 2016-01-26 00:01
Ah, I think I see the problem.

This arose from fixing a bug where `which` would prefer programs without a command extension over those that did have one, even though they were not actually executable on Windows.  So, for example, `mocha` would be preferred in some cases over `mocha.cmd`, but that was not the actual executable.

Since cross-spawn-async is using `which` to find programs that don't have extensions intentionally, this broke things.  The `isexe` module is (correctly) reporting that the script is not executable, and since there's no `.cmd` or whatever as a fallback, it's failing.

`which` lets you pass in a specific PATHEXT option, which would work around that, but that option is *not* passed further down the chain to isexe.  I'll land an update soon to address this, and then send a PR when it's safe to update the which version.

Sorry for not catching that!

**Comment by isaacs** [comment] 2016-01-26 02:15
Can you please try installing `npm i which@1.2.3` and see if that resolves the issue?

**Comment by isaacs** [comment] 2016-01-26 02:15
If it does, I'll move it from the `next` tag to `latest`, to fix anyone else running into this.

**Comment by satazor** [comment] 2016-01-26 08:14
https://ci.appveyor.com/project/satazor/node-cross-spawn-async/build/job/fxgt23f1o7ear27j

1.2.3 is still breaking :S

**Comment by satazor** [comment] 2016-01-26 08:20
@isaacs thanks for taking a look at this. appveyor is failing with both 1.2.2 and 1.2.3. I don't know it it is related to the reported issue or it is another one. I will investigate.

**Comment by satazor** [comment] 2016-01-26 08:47
Ok I narrowed down the problem. All tests are passing except the ones related to shebang's, that is, files with a shebang header that have execute bit set but have no extension. Since on windows there's no execute bit, `isexe` does not consider them. This causes which to report nullish for them which them causes my tests to fail.

For the purpose of `cross-spawn-async` if `mocha` file with shebang and execute bit on unix set is on the PATH, it also should be considered an executable on Windows.

@isaacs can you advise on what to do?

**Comment by isaacs** [comment] 2016-01-26 23:24
On windows, `isexe` doesn't use the file mode or look for an executable bit.  It *only* makes its choice based on the file extension being in the `env.PATHEXT` or `options.pathExt`.  If you have an empty string in that set, it passes for any file that exists.

```
c:\isexe>node
>  require('./').sync('index.js')
true
>  require('./').sync('README.md')
false
>  require('./').sync('README.md', { pathExt: ';' })
true
>  require('./').sync('README.md', { pathExt: process.env.PATHEXT + ';.MD' })
true
```

**Comment by isaacs** [comment] 2016-01-26 23:41
Ack, testing is hard.  Fixed on which 1.2.4.  I'd updated a typo in my windows VM, but it didn't make its way into the actual repo.

**Comment by satazor** [comment] 2016-01-27 01:08
Indeed I do pass ';<PATHEXT>' in https://github.com/IndigoUnited/node-cross-spawn-async/blob/master/lib/resolveCommand.js#L23

I can confirm that all tests are passing in 1.2.4! I will unlock the version now. Thanks @isaacs

**Comment by satazor** [comment] 2016-01-27 01:11
cross-spawn-async@1.2.8 released.

**Closed by satazor** 2016-01-27 01:11 UTC

**Comment by isaacs** [comment] 2016-01-27 02:11
Btw: this is the typo I was talking about.  Total head-slapper.  https://github.com/npm/node-which/commit/257dff20447aca250eb5aba6909507b133ae02c1

**Comment by satazor** [comment] 2016-01-27 07:41
I use linked folders on the VM and actually use an editor on it which diminuishes the probability for those kind of human errors. 

But I know what you mean, developing and mantaining cross platform modules such as which and cross-spawn are a pain in the ass for mac/linux devs.
